


const MOCK_DATA = [
    {
        id: 1,
        nombre: 'Vinilo Esmerilado',
        img:"https://www.mebac.com.ar/salta/wp-content/uploads/2020/02/47.08.006_1000-1-4.jpg",
        descripcion:"Esmerilado 200 Micrones alta Duracion",
        precio: 8500,
        category:'vinilo',
        stock: 50
        
    },
    {
        id: 2,
        nombre: 'Vinilo Microperforado',
        img: "https://http2.mlstatic.com/D_NQ_NP_806307-MLA49909865768_052022-O.jpg",
        descripcion:"Microperforado Italiano",
        precio: 9250,
        category:'vinilo',
        stock: 50
    },
    {
        id: 3,
        nombre: 'Lona Front 60 Oz',
        img: "https://tprint.com.uy/wp-content/uploads/2022/08/LONA-3.jpg",
        descripcion:"Lona 60 Oz Exterior",
        precio: 4970,
        category:'vinilo',
        stock: 50
    },
    {
        id: 4,
        nombre: 'Transfer Beige',
        img: "https://kinglobalprint.com/wp-content/uploads/2022/02/20210701_145603-scaled-1-1-scaled.jpg",
        descripcion:"Transfer Alto poder Adherente",
        precio: 6310,
        category:'transfer',
        stock: 8
    },
    {
        id: 5,
        nombre: 'Vinilo Calandrado',
        img: "https://www.proserart.com.ar/wordpress/wp-content/uploads/2013/01/vinilos-calandrados-462x375.jpg",
        descripcion:"Varios colores Oracal 651",
        precio: 3570,
        category:'vinilo',
        stock: 50
    },
    {
        id: 6,
        nombre: 'Placa pvc',
        img: "https://http2.mlstatic.com/D_NQ_NP_2X_706324-MLA53854714422_022023-F.webp",
        descripcion:"Placa pvc 2mm",
        precio: 15600,
        category:'plasticos',
        stock: 23
    },
    {
        id: 7,
        nombre: 'Acrilico 2,2',
        img: "https://coprodi.com.ar/nuevo/wp-content/uploads/2019/02/c2a2fff4-2106-4b6b-a874-eebd58ffb2e2.jpg",
        descripcion:"Acrilico 2,2 mm",
        precio: 25100,
        category:'plasticos',
        stock: 88
    },
    {
        id: 8,
        nombre: 'Transfer Beige',
        img: "https://ae01.alicdn.com/kf/S511b5138b1c24726b7efe3b138da798fp/Rollo-de-papel-de-transferencia-de-vinilo-adhesivo-transparente-con-rejilla-de-alineaci-n-azul-pegatina.jpg_Q90.jpg_.webpg",
        descripcion:"Transfer para MotR",
        precio: 1844,
        category:'transfer',
        stock: 2
    },
    
]

export default MOCK_DATA